### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by Ascynx**
Chest count overlay should now take into account vlado's lootcounter mod. Aka will work alongside it.

Might add other bugfixes to this if I find some more by the time it gets merged

### CODE REVIEW

**Comment by Njol** [comment]
Did you test this? Looking at vlado's mod, it looks like this won't be called at all.

**Comment by Ascynx** [comment]
it's tested

**Comment by Ascynx** [comment]
it's just looking for the edits made to the actionbar by vlado's mod

**Comment by Njol** [comment]
weird but if it works 🤷

**Comment by Ascynx** [comment]
it matches the red part in the edit
image
(\u00a7 is color code)

**Comment by Njol** [comment]
yeah, but that mod cancels the method, while our injection point is only at the end of the method, which I'd have though would then be skipped. I guess it must be different then ^^

**Comment by Ascynx** [comment]
it's odd but somehow it works, I could've technically just moved the inject to the start of the method but ehhhhh.

**Comment by Ascynx** [comment]
image
found out why I'm catching this, it cancels the old one and sends a new one which also goes through setOverlay

**Pull request merged**
