### PR TITLE
Update of current chest count and fixed officialName not being detected.

### PR DESCRIPTION
**Pull request by Ascynx**
(kinda my fault for the misunderstanding with Shard#toString())

### CODE REVIEW

**Comment by Njol** [comment]
Thanks! I didn't even realize the officialName issue ^^
I'll close this PR and perform the changes manually, as the merge would lead to an annoying merge conflict because the JSON formatting has changed.
I'll also test the resource reloader issue you've mentioned.

**Comment by Ascynx** [comment]
> I'll also test the resource reloader issue you've mentioned.

I had the issue the moment I created the resource reloader, though I haven't really tested it since though I think it still is an issue

**Comment by Njol** [comment]
I moved the reload from its own reloader into the RP reloader (where I put sprite reloading) and that works.

**Comment by Ascynx** [comment]
> I moved the reload from its own reloader into the RP reloader (where I put sprite reloading) and that works.

Fair enough

**Comment by Ascynx** [comment]
Also for calculator the close key is currently k by default but it seems I didn't make a config for it as well as it being detected in any gui making it possible to change the calculator state without being in an injected gui.

**Comment by Njol** [comment]
Already fixed that and added a config :)

**Pull request closed without merging**
